
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manzana
 */
public class Contrato extends javax.swing.JFrame {
    Contrat mContrat = new Contrat();
    BaseDeDatos mBaseDeDatos = new BaseDeDatos();
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelo2 = new DefaultTableModel();
    DefaultTableModel modelo3 = new DefaultTableModel();
    
    
    Client mCliente = new Client();
    public TableRowSorter<TableModel> modeloOrdenado;

    /**
     * Creates new form Contrato
     */
    public Contrato() {
        initComponents();
        setClienteBD();
        setEquipoBD();
        
        modelo3.addColumn("ID Equipo");
        modelo3.addColumn("Nombre");
        modelo3.addColumn("Tipo");
        modelo3.addColumn("Precio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IdContrato = new javax.swing.JTextField();
        HoraContrato = new javax.swing.JTextField();
        DuracionContrato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Lugar = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        AceptarContrato = new javax.swing.JButton();
        CancelarContrato = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TIC = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TCliente = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TEquipo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TSeleccion = new javax.swing.JTable();
        BAgregar = new javax.swing.JButton();
        TNumA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Contrato");

        jLabel2.setText("Fecha");

        jLabel3.setText("Hora");

        jLabel4.setText("Lugar");

        jLabel5.setText("Duracion");

        txt_Lugar.setColumns(20);
        txt_Lugar.setRows(5);
        jScrollPane1.setViewportView(txt_Lugar);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sonomil-icon.png"))); // NOI18N

        AceptarContrato.setText("Aceptar");
        AceptarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarContratoActionPerformed(evt);
            }
        });

        CancelarContrato.setText("Cancelar");
        CancelarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarContratoActionPerformed(evt);
            }
        });

        jLabel7.setText("ID Cliente");

        TCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TCliente);

        jLabel8.setText("Agregar Equipo");

        TEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TEquipoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TEquipo);

        TSeleccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(TSeleccion);

        BAgregar.setText("Agregar");
        BAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarActionPerformed(evt);
            }
        });

        TNumA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNumAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(HoraContrato)
                                .addComponent(IdContrato)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel6))
                            .addComponent(TIC, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DuracionContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AceptarContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelarContrato)
                .addGap(18, 18, 18)
                .addComponent(BAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TNumA, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(IdContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(HoraContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(DuracionContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(TIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarContrato)
                    .addComponent(CancelarContrato)
                    .addComponent(BAgregar)
                    .addComponent(TNumA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarContratoActionPerformed
        this.hide();
        Menu mMenu = new Menu();
        mMenu.show();
    }//GEN-LAST:event_CancelarContratoActionPerformed

    private void AceptarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarContratoActionPerformed
        
        mContrat.setIdContrato(this.IdContrato.getText());
        mContrat.setLugar(this.txt_Lugar.getText());
        mContrat.setFecha(this.jCalendar1.getDate().toString());
        mContrat.setHora(this.HoraContrato.getText());
        mContrat.setDuracion(this.DuracionContrato.getText());

        if (mBaseDeDatos.conectar()) {
            if (mBaseDeDatos.guardarContrato(mContrat)) {
                JOptionPane.showMessageDialog(rootPane, "Contrato Guardado con Exito");
            }
        }
    }//GEN-LAST:event_AceptarContratoActionPerformed

    private void TClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TClienteMouseClicked
        int rec = this.TCliente.getSelectedRow();
        this.TIC.setText(TCliente.getValueAt(rec, 0).toString());

    }//GEN-LAST:event_TClienteMouseClicked

    private void TEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEquipoMouseClicked
        if (evt.getClickCount()> 1)
            {
                System.out.println(TEquipo.getValueAt(TEquipo.getSelectedRow(), 0).toString());
            }
    }//GEN-LAST:event_TEquipoMouseClicked

    private void TNumAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNumAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNumAActionPerformed

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        Equipo mEquipo;
        int filaSeleccionada=TEquipo.getSelectedRow();
        mBaseDeDatos.conectar();
        String [] DatosS;
        
        int NE = (Integer.parseInt(this.TNumA.getText()));
        
        /*modelo3.addColumn("ID Equipo");
        modelo3.addColumn("Nombre");
        modelo3.addColumn("Tipo");*/

       if (filaSeleccionada>=0) {
        DatosS = new String[4];
        //mEquipo = (Equipo)mEquipoArrays;
        DatosS[0] = TEquipo.getValueAt(filaSeleccionada, 0).toString();
        DatosS[1] = TEquipo.getValueAt(filaSeleccionada, 1).toString();
        DatosS[2] = TEquipo.getValueAt(filaSeleccionada, 2).toString();
        DatosS[3] = Integer.toString((NE) * Integer.parseInt(TEquipo.getValueAt(filaSeleccionada, 3).toString()));
  
          modelo3.addRow(DatosS);
         // modeloOrdenado = new TableRowSorter<TableModel>(modelo);
    //tabla.setRowSorter(modeloOrdenado);
		//modeloOrdenado.setRowFilter(RowFilter.regexFilter("^a", 0));
    }

    this.TSeleccion.setModel(modelo3);
    this.TSeleccion.getColumnModel().getColumn(0).setPreferredWidth(80);
    this.TSeleccion.getColumnModel().getColumn(1).setPreferredWidth(200);
    this.TSeleccion.getColumnModel().getColumn(2).setPreferredWidth(200);
    this.TSeleccion.getColumnModel().getColumn(3).setPreferredWidth(200);
        
    }//GEN-LAST:event_BAgregarActionPerformed

    public void setClienteBD(){
        Client mCliente;
        mBaseDeDatos.conectar();
        ArrayList mArrayList = new ArrayList();
        mArrayList = mBaseDeDatos.consultarCliente();
        String [] DatosC;
        
        modelo2.addColumn("ID Cliente");
        modelo2.addColumn("Nombre");
        modelo2.addColumn("Telefono");

    for (Object mClienteArrays : mArrayList) {
    DatosC = new String[3];
    mCliente = (Client)mClienteArrays;
    DatosC[0] = mCliente.getIdC();
    DatosC[1] = mCliente.getNombreC();
    DatosC[2] = mCliente.getTelefonoC();
  
    modelo2.addRow(DatosC);
    modeloOrdenado = new TableRowSorter<TableModel>(modelo2);
    //tabla.setRowSorter(modeloOrdenado);
		modeloOrdenado.setRowFilter(RowFilter.regexFilter("^a", 0));
    }

    this.TCliente.setModel(modelo2);
    this.TCliente.getColumnModel().getColumn(0).setPreferredWidth(50);
    this.TCliente.getColumnModel().getColumn(1).setPreferredWidth(200);
    this.TCliente.getColumnModel().getColumn(2).setPreferredWidth(100);

    if (this.TCliente.getRowCount() > 0) {
    //this.jTabla.RowFilter.regexFilter("^a", 0);
    this.TCliente.setRowSelectionInterval(0, 0);}
        
        
        
    }
    
    public void setEquipoBD(){
        Equipo mEquipo;
        mBaseDeDatos.conectar();
        ArrayList mEquipoArray = mBaseDeDatos.consultarEquipo();
        String [] DatosE;
        
        modelo.addColumn("ID Equipo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Tipo");
        modelo.addColumn("Precio");

    for (Object mEquipoArrays : mEquipoArray) {
    DatosE = new String[4];
    mEquipo = (Equipo)mEquipoArrays;
    DatosE[0] = mEquipo.getId_Equipo();
    DatosE[1] = mEquipo.getNombreE();
    DatosE[2] = mEquipo.getTipo();
    DatosE[3] = Integer.toString(mEquipo.getPrecio());
  
    modelo.addRow(DatosE);
    modeloOrdenado = new TableRowSorter<TableModel>(modelo);
    //tabla.setRowSorter(modeloOrdenado);
		modeloOrdenado.setRowFilter(RowFilter.regexFilter("^a", 0));
    }

    this.TEquipo.setModel(modelo);
    this.TEquipo.getColumnModel().getColumn(0).setPreferredWidth(80);
    this.TEquipo.getColumnModel().getColumn(1).setPreferredWidth(200);
    this.TEquipo.getColumnModel().getColumn(2).setPreferredWidth(200);
    this.TEquipo.getColumnModel().getColumn(3).setPreferredWidth(200);

    if (this.TEquipo.getRowCount() > 0) {
    //this.jTabla.RowFilter.regexFilter("^a", 0);
    this.TEquipo.setRowSelectionInterval(0, 0);}
        
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contrato().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarContrato;
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton CancelarContrato;
    private javax.swing.JTextField DuracionContrato;
    private javax.swing.JTextField HoraContrato;
    private javax.swing.JTextField IdContrato;
    private javax.swing.JTable TCliente;
    private javax.swing.JTable TEquipo;
    private javax.swing.JTextField TIC;
    private javax.swing.JTextField TNumA;
    private javax.swing.JTable TSeleccion;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txt_Lugar;
    // End of variables declaration//GEN-END:variables
}
